apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: devops-assignment
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
