apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: devops-assignment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask
        image: akshatranakoti032002/flask-mongo:v1   # 👈 your real image
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongodb-uri
        resources:
          requests:
            cpu: "200m"
            memory: "250Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
